# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.liquidation import Liquidation

class TestLiquidation(unittest.TestCase):
    """Liquidation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Liquidation:
        """Test Liquidation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Liquidation`
        """
        model = Liquidation()
        if include_optional:
            return Liquidation(
                liquidation_id = 1,
                account_index = 1,
                liquidation_type = 1,
                portfolio_value = '1',
                margin_requirement = '1'
            )
        else:
            return Liquidation(
                liquidation_id = 1,
                account_index = 1,
                liquidation_type = 1,
                portfolio_value = '1',
                margin_requirement = '1',
        )
        """

    def testLiquidation(self):
        """Test Liquidation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
