# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.api_key import ApiKey

class TestApiKey(unittest.TestCase):
    """ApiKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKey:
        """Test ApiKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKey`
        """
        model = ApiKey()
        if include_optional:
            return ApiKey(
                account_index = 3,
                api_key_index = 0,
                nonce = 722,
                public_key = ''
            )
        else:
            return ApiKey(
                account_index = 3,
                api_key_index = 0,
                nonce = 722,
                public_key = '',
        )
        """

    def testApiKey(self):
        """Test ApiKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
