# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.order_book_orders import OrderBookOrders

class TestOrderBookOrders(unittest.TestCase):
    """OrderBookOrders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderBookOrders:
        """Test OrderBookOrders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderBookOrders`
        """
        model = OrderBookOrders()
        if include_optional:
            return OrderBookOrders(
                code = 200,
                message = '',
                total_asks = 1,
                asks = [
                    lighter.models.simple_order.SimpleOrder(
                        order_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        remaining_base_amount = '0.1', 
                        price = '3024.66', 
                        order_expiry = 1640995200, )
                    ],
                total_bids = 1,
                bids = [
                    lighter.models.simple_order.SimpleOrder(
                        order_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        remaining_base_amount = '0.1', 
                        price = '3024.66', 
                        order_expiry = 1640995200, )
                    ]
            )
        else:
            return OrderBookOrders(
                code = 200,
                total_asks = 1,
                asks = [
                    lighter.models.simple_order.SimpleOrder(
                        order_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        remaining_base_amount = '0.1', 
                        price = '3024.66', 
                        order_expiry = 1640995200, )
                    ],
                total_bids = 1,
                bids = [
                    lighter.models.simple_order.SimpleOrder(
                        order_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        remaining_base_amount = '0.1', 
                        price = '3024.66', 
                        order_expiry = 1640995200, )
                    ],
        )
        """

    def testOrderBookOrders(self):
        """Test OrderBookOrders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
