# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_account(self) -> None:
        """Test case for account

        account
        """
        pass

    def test_accounts(self) -> None:
        """Test case for accounts

        accounts
        """
        pass

    def test_accounts_by_l1_address(self) -> None:
        """Test case for accounts_by_l1_address

        accountsByL1Address
        """
        pass

    def test_apikeys(self) -> None:
        """Test case for apikeys

        apikeys
        """
        pass

    def test_fee_bucket(self) -> None:
        """Test case for fee_bucket

        feeBucket
        """
        pass

    def test_is_whitelisted(self) -> None:
        """Test case for is_whitelisted

        isWhitelisted
        """
        pass

    def test_pnl(self) -> None:
        """Test case for pnl

        pnl
        """
        pass

    def test_public_pools(self) -> None:
        """Test case for public_pools

        publicPools
        """
        pass


if __name__ == '__main__':
    unittest.main()
