# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.public_pool_info import PublicPoolInfo

class TestPublicPoolInfo(unittest.TestCase):
    """PublicPoolInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicPoolInfo:
        """Test PublicPoolInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicPoolInfo`
        """
        model = PublicPoolInfo()
        if include_optional:
            return PublicPoolInfo(
                status = 0,
                operator_fee = '100',
                min_operator_share_rate = '200',
                total_shares = 100000,
                operator_shares = 20000
            )
        else:
            return PublicPoolInfo(
                status = 0,
                operator_fee = '100',
                min_operator_share_rate = '200',
                total_shares = 100000,
                operator_shares = 20000,
        )
        """

    def testPublicPoolInfo(self):
        """Test PublicPoolInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
