# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.detailed_account import DetailedAccount

class TestDetailedAccount(unittest.TestCase):
    """DetailedAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedAccount:
        """Test DetailedAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedAccount`
        """
        model = DetailedAccount()
        if include_optional:
            return DetailedAccount(
                code = 200,
                message = '',
                account_type = 1,
                index = 1,
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                cancel_all_time = 1640995200,
                total_order_count = 100,
                pending_order_count = 100,
                status = 1,
                collateral = '46342',
                name = '',
                description = '',
                positions = [
                    lighter.models.account_position.AccountPosition(
                        market_id = 1, 
                        symbol = 'ETH', 
                        initial_margin_fraction = '20.00', 
                        open_order_count = 3, 
                        pending_order_count = 3, 
                        sign = 1, 
                        position = '3.6956', 
                        avg_entry_price = '3024.66', 
                        position_value = '3019.92', 
                        unrealized_pnl = '17.521309', 
                        realized_pnl = '2.000000', )
                    ],
                total_asset_value = '19995',
                market_stats = [
                    lighter.models.account_market_stats.AccountMarketStats(
                        market_id = 1, 
                        daily_trades_count = 68, 
                        daily_base_token_volume = 235.25, 
                        daily_quote_token_volume = 93566.25, )
                    ],
                pool_info = lighter.models.public_pool_info.PublicPoolInfo(
                    status = 0, 
                    operator_fee = '100', 
                    min_operator_share_rate = '200', 
                    total_shares = 100000, 
                    operator_shares = 20000, ),
                shares = [
                    lighter.models.public_pool_share.PublicPoolShare(
                        public_pool_index = 1, 
                        shares_amount = 3000, 
                        entry_usdc = '3000', )
                    ]
            )
        else:
            return DetailedAccount(
                code = 200,
                account_type = 1,
                index = 1,
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                cancel_all_time = 1640995200,
                total_order_count = 100,
                pending_order_count = 100,
                status = 1,
                collateral = '46342',
                name = '',
                description = '',
                positions = [
                    lighter.models.account_position.AccountPosition(
                        market_id = 1, 
                        symbol = 'ETH', 
                        initial_margin_fraction = '20.00', 
                        open_order_count = 3, 
                        pending_order_count = 3, 
                        sign = 1, 
                        position = '3.6956', 
                        avg_entry_price = '3024.66', 
                        position_value = '3019.92', 
                        unrealized_pnl = '17.521309', 
                        realized_pnl = '2.000000', )
                    ],
                total_asset_value = '19995',
                market_stats = [
                    lighter.models.account_market_stats.AccountMarketStats(
                        market_id = 1, 
                        daily_trades_count = 68, 
                        daily_base_token_volume = 235.25, 
                        daily_quote_token_volume = 93566.25, )
                    ],
                pool_info = lighter.models.public_pool_info.PublicPoolInfo(
                    status = 0, 
                    operator_fee = '100', 
                    min_operator_share_rate = '200', 
                    total_shares = 100000, 
                    operator_shares = 20000, ),
                shares = [
                    lighter.models.public_pool_share.PublicPoolShare(
                        public_pool_index = 1, 
                        shares_amount = 3000, 
                        entry_usdc = '3000', )
                    ],
        )
        """

    def testDetailedAccount(self):
        """Test DetailedAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
