# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.account_position import AccountPosition

class TestAccountPosition(unittest.TestCase):
    """AccountPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountPosition:
        """Test AccountPosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountPosition`
        """
        model = AccountPosition()
        if include_optional:
            return AccountPosition(
                market_id = 1,
                symbol = 'ETH',
                initial_margin_fraction = '20.00',
                open_order_count = 3,
                pending_order_count = 3,
                sign = 1,
                position = '3.6956',
                avg_entry_price = '3024.66',
                position_value = '3019.92',
                unrealized_pnl = '17.521309',
                realized_pnl = '2.000000'
            )
        else:
            return AccountPosition(
                market_id = 1,
                symbol = 'ETH',
                initial_margin_fraction = '20.00',
                open_order_count = 3,
                pending_order_count = 3,
                sign = 1,
                position = '3.6956',
                avg_entry_price = '3024.66',
                position_value = '3019.92',
                unrealized_pnl = '17.521309',
                realized_pnl = '2.000000',
        )
        """

    def testAccountPosition(self):
        """Test AccountPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
