# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_deposit_history import ReqGetDepositHistory

class TestReqGetDepositHistory(unittest.TestCase):
    """ReqGetDepositHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetDepositHistory:
        """Test ReqGetDepositHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetDepositHistory`
        """
        model = ReqGetDepositHistory()
        if include_optional:
            return ReqGetDepositHistory(
                l1_address = '',
                cursor = '',
                filter = 'all'
            )
        else:
            return ReqGetDepositHistory(
                l1_address = '',
        )
        """

    def testReqGetDepositHistory(self):
        """Test ReqGetDepositHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
