# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.layer2_basic_info import Layer2BasicInfo

class TestLayer2BasicInfo(unittest.TestCase):
    """Layer2BasicInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Layer2BasicInfo:
        """Test Layer2BasicInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Layer2BasicInfo`
        """
        model = Layer2BasicInfo()
        if include_optional:
            return Layer2BasicInfo(
                code = 200,
                message = '',
                block_committed = 45434,
                block_verified = 45434,
                total_transaction_count = 75434
            )
        else:
            return Layer2BasicInfo(
                code = 200,
                block_committed = 45434,
                block_verified = 45434,
                total_transaction_count = 75434,
        )
        """

    def testLayer2BasicInfo(self):
        """Test Layer2BasicInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
