# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.bridge_supported_network import BridgeSupportedNetwork

class TestBridgeSupportedNetwork(unittest.TestCase):
    """BridgeSupportedNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BridgeSupportedNetwork:
        """Test BridgeSupportedNetwork
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BridgeSupportedNetwork`
        """
        model = BridgeSupportedNetwork()
        if include_optional:
            return BridgeSupportedNetwork(
                name = 'Arbitrum',
                chain_id = '4164',
                explorer = 'https://arbiscan.io/'
            )
        else:
            return BridgeSupportedNetwork(
                name = 'Arbitrum',
                chain_id = '4164',
                explorer = 'https://arbiscan.io/',
        )
        """

    def testBridgeSupportedNetwork(self):
        """Test BridgeSupportedNetwork"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
