# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.root_api import RootApi


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RootApi()

    def tearDown(self) -> None:
        pass

    def test_info(self) -> None:
        """Test case for info

        info
        """
        pass

    def test_status(self) -> None:
        """Test case for status

        status
        """
        pass


if __name__ == '__main__':
    unittest.main()
