# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_account_by_l1_address import ReqGetAccountByL1Address

class TestReqGetAccountByL1Address(unittest.TestCase):
    """ReqGetAccountByL1Address unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetAccountByL1Address:
        """Test ReqGetAccountByL1Address
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetAccountByL1Address`
        """
        model = ReqGetAccountByL1Address()
        if include_optional:
            return ReqGetAccountByL1Address(
                l1_address = ''
            )
        else:
            return ReqGetAccountByL1Address(
                l1_address = '',
        )
        """

    def testReqGetAccountByL1Address(self):
        """Test ReqGetAccountByL1Address"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
