# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.withdraw_history import WithdrawHistory

class TestWithdrawHistory(unittest.TestCase):
    """WithdrawHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawHistory:
        """Test WithdrawHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithdrawHistory`
        """
        model = WithdrawHistory()
        if include_optional:
            return WithdrawHistory(
                code = 200,
                message = '',
                withdraws = [
                    lighter.models.withdraw_history_item.WithdrawHistoryItem(
                        id = '', 
                        amount = '0.1', 
                        timestamp = 1640995200, 
                        status = 'failed', 
                        type = 'secure', )
                    ],
                cursor = lighter.models.withdraw_history_cursor.WithdrawHistoryCursor(
                    secure_id = '1', 
                    fast_id = '1', )
            )
        else:
            return WithdrawHistory(
                code = 200,
                withdraws = [
                    lighter.models.withdraw_history_item.WithdrawHistoryItem(
                        id = '', 
                        amount = '0.1', 
                        timestamp = 1640995200, 
                        status = 'failed', 
                        type = 'secure', )
                    ],
                cursor = lighter.models.withdraw_history_cursor.WithdrawHistoryCursor(
                    secure_id = '1', 
                    fast_id = '1', ),
        )
        """

    def testWithdrawHistory(self):
        """Test WithdrawHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
