# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_fundings import ReqGetFundings

class TestReqGetFundings(unittest.TestCase):
    """ReqGetFundings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetFundings:
        """Test ReqGetFundings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetFundings`
        """
        model = ReqGetFundings()
        if include_optional:
            return ReqGetFundings(
                market_id = 56,
                resolution = '1h',
                start_timestamp = 56,
                end_timestamp = 56,
                count_back = 56
            )
        else:
            return ReqGetFundings(
                market_id = 56,
                resolution = '1h',
                start_timestamp = 56,
                end_timestamp = 56,
                count_back = 56,
        )
        """

    def testReqGetFundings(self):
        """Test ReqGetFundings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
