# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.sub_accounts import SubAccounts

class TestSubAccounts(unittest.TestCase):
    """SubAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubAccounts:
        """Test SubAccounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubAccounts`
        """
        model = SubAccounts()
        if include_optional:
            return SubAccounts(
                code = 200,
                message = '',
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                sub_accounts = 1
            )
        else:
            return SubAccounts(
                code = 200,
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                sub_accounts = 1,
        )
        """

    def testSubAccounts(self):
        """Test SubAccounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
