# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.pn_l_entry import PnLEntry

class TestPnLEntry(unittest.TestCase):
    """PnLEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PnLEntry:
        """Test PnLEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PnLEntry`
        """
        model = PnLEntry()
        if include_optional:
            return PnLEntry(
                timestamp = 1640995200,
                value = 12.0
            )
        else:
            return PnLEntry(
                timestamp = 1640995200,
                value = 12.0,
        )
        """

    def testPnLEntry(self):
        """Test PnLEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
