# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.orders import Orders

class TestOrders(unittest.TestCase):
    """Orders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Orders:
        """Test Orders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Orders`
        """
        model = Orders()
        if include_optional:
            return Orders(
                code = 200,
                message = '',
                next_cursor = '',
                orders = [
                    lighter.models.order.Order(
                        order_index = 1, 
                        client_order_index = 234, 
                        market_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        price = '3024.66', 
                        nonce = 722, 
                        remaining_base_amount = '0.1', 
                        is_ask = True, 
                        base_size = 12354, 
                        base_price = 3024, 
                        filled_base_amount = '0.1', 
                        filled_quote_amount = '0.1', 
                        side = 'buy', 
                        type = 'limit', 
                        time_in_force = 'good-till-time', 
                        reduce_only = True, 
                        trigger_price = '3024.66', 
                        order_expiry = 1640995200, 
                        status = 'open', 
                        trigger_time = 1640995200, 
                        parent_order_index = 1, 
                        block_height = 45434, 
                        timestamp = 1640995200, )
                    ]
            )
        else:
            return Orders(
                code = 200,
                orders = [
                    lighter.models.order.Order(
                        order_index = 1, 
                        client_order_index = 234, 
                        market_index = 1, 
                        owner_account_index = 1, 
                        initial_base_amount = '0.1', 
                        price = '3024.66', 
                        nonce = 722, 
                        remaining_base_amount = '0.1', 
                        is_ask = True, 
                        base_size = 12354, 
                        base_price = 3024, 
                        filled_base_amount = '0.1', 
                        filled_quote_amount = '0.1', 
                        side = 'buy', 
                        type = 'limit', 
                        time_in_force = 'good-till-time', 
                        reduce_only = True, 
                        trigger_price = '3024.66', 
                        order_expiry = 1640995200, 
                        status = 'open', 
                        trigger_time = 1640995200, 
                        parent_order_index = 1, 
                        block_height = 45434, 
                        timestamp = 1640995200, )
                    ],
        )
        """

    def testOrders(self):
        """Test Orders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
