# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_account_pending_txs import ReqGetAccountPendingTxs

class TestReqGetAccountPendingTxs(unittest.TestCase):
    """ReqGetAccountPendingTxs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetAccountPendingTxs:
        """Test ReqGetAccountPendingTxs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetAccountPendingTxs`
        """
        model = ReqGetAccountPendingTxs()
        if include_optional:
            return ReqGetAccountPendingTxs(
                by = 'account_index',
                value = '',
                types = [
                    56
                    ]
            )
        else:
            return ReqGetAccountPendingTxs(
        )
        """

    def testReqGetAccountPendingTxs(self):
        """Test ReqGetAccountPendingTxs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
