# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.public_pool import PublicPool

class TestPublicPool(unittest.TestCase):
    """PublicPool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicPool:
        """Test PublicPool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicPool`
        """
        model = PublicPool()
        if include_optional:
            return PublicPool(
                code = 200,
                message = '',
                account_type = 1,
                index = 1,
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                cancel_all_time = 1640995200,
                total_order_count = 100,
                pending_order_count = 100,
                status = 1,
                collateral = '46342',
                name = '',
                description = '',
                total_asset_value = '19995',
                pool_info = lighter.models.public_pool_info.PublicPoolInfo(
                    status = 0, 
                    operator_fee = '100', 
                    min_operator_share_rate = '200', 
                    total_shares = 100000, 
                    operator_shares = 20000, ),
                account_share = lighter.models.public_pool_share.PublicPoolShare(
                    public_pool_index = 1, 
                    shares_amount = 3000, 
                    entry_usdc = '3000', )
            )
        else:
            return PublicPool(
                code = 200,
                account_type = 1,
                index = 1,
                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
                cancel_all_time = 1640995200,
                total_order_count = 100,
                pending_order_count = 100,
                status = 1,
                collateral = '46342',
                name = '',
                description = '',
                total_asset_value = '19995',
                pool_info = lighter.models.public_pool_info.PublicPoolInfo(
                    status = 0, 
                    operator_fee = '100', 
                    min_operator_share_rate = '200', 
                    total_shares = 100000, 
                    operator_shares = 20000, ),
                account_share = lighter.models.public_pool_share.PublicPoolShare(
                    public_pool_index = 1, 
                    shares_amount = 3000, 
                    entry_usdc = '3000', ),
        )
        """

    def testPublicPool(self):
        """Test PublicPool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
