# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_account_inactive_orders import ReqGetAccountInactiveOrders

class TestReqGetAccountInactiveOrders(unittest.TestCase):
    """ReqGetAccountInactiveOrders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetAccountInactiveOrders:
        """Test ReqGetAccountInactiveOrders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetAccountInactiveOrders`
        """
        model = ReqGetAccountInactiveOrders()
        if include_optional:
            return ReqGetAccountInactiveOrders(
                account_index = 56,
                market_id = 56,
                ask_filter = 56,
                between_timestamps = '',
                cursor = '',
                limit = 1
            )
        else:
            return ReqGetAccountInactiveOrders(
                account_index = 56,
                limit = 1,
        )
        """

    def testReqGetAccountInactiveOrders(self):
        """Test ReqGetAccountInactiveOrders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
