# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.candlesticks import Candlesticks

class TestCandlesticks(unittest.TestCase):
    """Candlesticks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Candlesticks:
        """Test Candlesticks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Candlesticks`
        """
        model = Candlesticks()
        if include_optional:
            return Candlesticks(
                code = 200,
                message = '',
                resolution = '15m',
                candlesticks = [
                    lighter.models.candlestick.Candlestick(
                        timestamp = 1640995200, 
                        open = 3024.66, 
                        high = 3034.66, 
                        low = 3014.66, 
                        close = 3024.66, 
                        volume0 = 235.25, 
                        volume1 = 93566.25, 
                        last_trade_id = 1, )
                    ]
            )
        else:
            return Candlesticks(
                code = 200,
                resolution = '15m',
                candlesticks = [
                    lighter.models.candlestick.Candlestick(
                        timestamp = 1640995200, 
                        open = 3024.66, 
                        high = 3034.66, 
                        low = 3014.66, 
                        close = 3024.66, 
                        volume0 = 235.25, 
                        volume1 = 93566.25, 
                        last_trade_id = 1, )
                    ],
        )
        """

    def testCandlesticks(self):
        """Test Candlesticks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
