# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.fundings import Fundings

class TestFundings(unittest.TestCase):
    """Fundings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Fundings:
        """Test Fundings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Fundings`
        """
        model = Fundings()
        if include_optional:
            return Fundings(
                code = 200,
                message = '',
                resolution = '1h',
                fundings = [
                    lighter.models.funding.Funding(
                        timestamp = 1640995200, 
                        value = '0.0001', 
                        rate = '0.0001', 
                        direction = 'long', )
                    ]
            )
        else:
            return Fundings(
                code = 200,
                resolution = '1h',
                fundings = [
                    lighter.models.funding.Funding(
                        timestamp = 1640995200, 
                        value = '0.0001', 
                        rate = '0.0001', 
                        direction = 'long', )
                    ],
        )
        """

    def testFundings(self):
        """Test Fundings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
