# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.zk_lighter_info import ZkLighterInfo

class TestZkLighterInfo(unittest.TestCase):
    """ZkLighterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZkLighterInfo:
        """Test ZkLighterInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZkLighterInfo`
        """
        model = ZkLighterInfo()
        if include_optional:
            return ZkLighterInfo(
                contract_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
            )
        else:
            return ZkLighterInfo(
                contract_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
        )
        """

    def testZkLighterInfo(self):
        """Test ZkLighterInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
