# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.blocks import Blocks

class TestBlocks(unittest.TestCase):
    """Blocks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Blocks:
        """Test Blocks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Blocks`
        """
        model = Blocks()
        if include_optional:
            return Blocks(
                code = 200,
                message = '',
                total = 56,
                blocks = [
                    lighter.models.block.Block(
                        commitment = '', 
                        height = 56, 
                        state_root = '', 
                        priority_operations = 56, 
                        on_chain_l2_operations = 56, 
                        pending_on_chain_operations_pub_data = '', 
                        committed_tx_hash = '', 
                        committed_at = 56, 
                        verified_tx_hash = '', 
                        verified_at = 56, 
                        txs = [
                            lighter.models.tx.Tx(
                                hash = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                                type = 1, 
                                info = '{}', 
                                event_info = '{}', 
                                status = 1, 
                                transaction_index = 8761, 
                                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                                account_index = 1, 
                                nonce = 722, 
                                expire_at = 1640995200, 
                                block_height = 45434, 
                                queued_at = 1640995200, 
                                executed_at = 1640995200, 
                                sequence_index = 8761, 
                                parent_hash = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', )
                            ], 
                        status = 56, 
                        size = 56, )
                    ]
            )
        else:
            return Blocks(
                code = 200,
                total = 56,
                blocks = [
                    lighter.models.block.Block(
                        commitment = '', 
                        height = 56, 
                        state_root = '', 
                        priority_operations = 56, 
                        on_chain_l2_operations = 56, 
                        pending_on_chain_operations_pub_data = '', 
                        committed_tx_hash = '', 
                        committed_at = 56, 
                        verified_tx_hash = '', 
                        verified_at = 56, 
                        txs = [
                            lighter.models.tx.Tx(
                                hash = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                                type = 1, 
                                info = '{}', 
                                event_info = '{}', 
                                status = 1, 
                                transaction_index = 8761, 
                                l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                                account_index = 1, 
                                nonce = 722, 
                                expire_at = 1640995200, 
                                block_height = 45434, 
                                queued_at = 1640995200, 
                                executed_at = 1640995200, 
                                sequence_index = 8761, 
                                parent_hash = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', )
                            ], 
                        status = 56, 
                        size = 56, )
                    ],
        )
        """

    def testBlocks(self):
        """Test Blocks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
