# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.position_funding import PositionFunding

class TestPositionFunding(unittest.TestCase):
    """PositionFunding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionFunding:
        """Test PositionFunding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionFunding`
        """
        model = PositionFunding()
        if include_optional:
            return PositionFunding(
                timestamp = 1640995200,
                market_id = 1,
                funding_id = 1,
                change = '1',
                rate = '1',
                position_size = '1',
                position_side = 'long'
            )
        else:
            return PositionFunding(
                timestamp = 1640995200,
                market_id = 1,
                funding_id = 1,
                change = '1',
                rate = '1',
                position_size = '1',
                position_side = 'long',
        )
        """

    def testPositionFunding(self):
        """Test PositionFunding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
