# coding: utf-8

"""
    Lighter API

    Public APIs for Lighter

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.account import Account

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                code = 100,
                total = 1,
                accounts = [
                    lighter.models.single_account.SingleAccount(
                        code = 56, 
                        index = 56, 
                        l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                        pk = '3ad126b9f0a2cc8cb367ef67a6c77389a85e18e20ce8da2edf34d022e9bf1aa8', 
                        status = 1, 
                        nonce = 722, 
                        collateral = '', 
                        positions = [
                            lighter.models.account_position.AccountPosition(
                                market_id = 0, 
                                name = 'Ethereum', 
                                symbol = 'ETH', 
                                sign = -1, 
                                position = '3.6955', 
                                ask_order_size = '58933.9753', 
                                bid_order_size = '59010.2588', 
                                avg_entry_price = '3024.66', 
                                market_value = '3019.92', 
                                unrealized_pnl = '17.521309', 
                                realized_pnl = '0.000000', )
                            ], 
                        total_asset_value = '199955234976240000000000000', 
                        market_stats = [
                            lighter.models.account_market_stats.AccountMarketStats(
                                market_id = 1, 
                                daily_trades_count = 68, 
                                daily_base_token_volume = 235.25, 
                                daily_quote_token_volume = 93566.25, 
                                open_position_base = 93.0, 
                                open_position_quote = 1276.0, )
                            ], )
                    ]
            )
        else:
            return Account(
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
