# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.order_book_detail import OrderBookDetail

class TestOrderBookDetail(unittest.TestCase):
    """OrderBookDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderBookDetail:
        """Test OrderBookDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderBookDetail`
        """
        model = OrderBookDetail()
        if include_optional:
            return OrderBookDetail(
                symbol = 'ETH',
                market_id = 1,
                status = 'active',
                taker_fee = '0.0001',
                maker_fee = '0.0000',
                liquidation_fee = '0.01',
                min_base_amount = '0.01',
                min_quote_amount = '0.1',
                supported_size_decimals = 4,
                supported_price_decimals = 4,
                supported_quote_decimals = 4,
                size_decimals = 4,
                price_decimals = 4,
                quote_multiplier = 10000,
                default_initial_margin_fraction = 100,
                min_initial_margin_fraction = 100,
                maintenance_margin_fraction = 50,
                closeout_margin_fraction = 100,
                last_trade_price = 3024.66,
                daily_trades_count = 68,
                daily_base_token_volume = 235.25,
                daily_quote_token_volume = 93566.25,
                daily_price_low = 3014.66,
                daily_price_high = 3024.66,
                daily_price_change = 3.66,
                open_interest = 93.0,
                daily_chart = "{1640995200:3024.66}"
            )
        else:
            return OrderBookDetail(
                symbol = 'ETH',
                market_id = 1,
                status = 'active',
                taker_fee = '0.0001',
                maker_fee = '0.0000',
                liquidation_fee = '0.01',
                min_base_amount = '0.01',
                min_quote_amount = '0.1',
                supported_size_decimals = 4,
                supported_price_decimals = 4,
                supported_quote_decimals = 4,
                size_decimals = 4,
                price_decimals = 4,
                quote_multiplier = 10000,
                default_initial_margin_fraction = 100,
                min_initial_margin_fraction = 100,
                maintenance_margin_fraction = 50,
                closeout_margin_fraction = 100,
                last_trade_price = 3024.66,
                daily_trades_count = 68,
                daily_base_token_volume = 235.25,
                daily_quote_token_volume = 93566.25,
                daily_price_low = 3014.66,
                daily_price_high = 3024.66,
                daily_price_change = 3.66,
                open_interest = 93.0,
                daily_chart = "{1640995200:3024.66}",
        )
        """

    def testOrderBookDetail(self):
        """Test OrderBookDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
