# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.funding import Funding

class TestFunding(unittest.TestCase):
    """Funding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Funding:
        """Test Funding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Funding`
        """
        model = Funding()
        if include_optional:
            return Funding(
                timestamp = 1640995200,
                value = '0.0001',
                rate = '0.0001',
                direction = 'long'
            )
        else:
            return Funding(
                timestamp = 1640995200,
                value = '0.0001',
                rate = '0.0001',
                direction = 'long',
        )
        """

    def testFunding(self):
        """Test Funding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
