# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.transaction_api import TransactionApi


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionApi()

    def tearDown(self) -> None:
        pass

    def test_account_pending_txs(self) -> None:
        """Test case for account_pending_txs

        accountPendingTxs
        """
        pass

    def test_account_txs(self) -> None:
        """Test case for account_txs

        accountTxs
        """
        pass

    def test_block_txs(self) -> None:
        """Test case for block_txs

        blockTxs
        """
        pass

    def test_deposit_history(self) -> None:
        """Test case for deposit_history

        deposit_history
        """
        pass

    def test_next_nonce(self) -> None:
        """Test case for next_nonce

        nextNonce
        """
        pass

    def test_pending_txs(self) -> None:
        """Test case for pending_txs

        pendingTxs
        """
        pass

    def test_send_tx(self) -> None:
        """Test case for send_tx

        sendTx
        """
        pass

    def test_send_tx_batch(self) -> None:
        """Test case for send_tx_batch

        sendTxBatch
        """
        pass

    def test_tx(self) -> None:
        """Test case for tx

        tx
        """
        pass

    def test_tx_from_l1_tx_hash(self) -> None:
        """Test case for tx_from_l1_tx_hash

        txFromL1TxHash
        """
        pass

    def test_txs(self) -> None:
        """Test case for txs

        txs
        """
        pass

    def test_withdraw_history(self) -> None:
        """Test case for withdraw_history

        withdraw_history
        """
        pass


if __name__ == '__main__':
    unittest.main()
