# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_order_books import ReqGetOrderBooks

class TestReqGetOrderBooks(unittest.TestCase):
    """ReqGetOrderBooks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetOrderBooks:
        """Test ReqGetOrderBooks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetOrderBooks`
        """
        model = ReqGetOrderBooks()
        if include_optional:
            return ReqGetOrderBooks(
                market_id = 56
            )
        else:
            return ReqGetOrderBooks(
        )
        """

    def testReqGetOrderBooks(self):
        """Test ReqGetOrderBooks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
