# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.candlestick_api import CandlestickApi


class TestCandlestickApi(unittest.TestCase):
    """CandlestickApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CandlestickApi()

    def tearDown(self) -> None:
        pass

    def test_candlesticks(self) -> None:
        """Test case for candlesticks

        candlesticks
        """
        pass

    def test_fundings(self) -> None:
        """Test case for fundings

        fundings
        """
        pass


if __name__ == '__main__':
    unittest.main()
