# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.order_api import OrderApi


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrderApi()

    def tearDown(self) -> None:
        pass

    def test_account_active_orders(self) -> None:
        """Test case for account_active_orders

        accountActiveOrders
        """
        pass

    def test_account_inactive_orders(self) -> None:
        """Test case for account_inactive_orders

        accountInactiveOrders
        """
        pass

    def test_account_orders(self) -> None:
        """Test case for account_orders

        accountOrders
        """
        pass

    def test_exchange_stats(self) -> None:
        """Test case for exchange_stats

        exchangeStats
        """
        pass

    def test_order_book_details(self) -> None:
        """Test case for order_book_details

        orderBookDetails
        """
        pass

    def test_order_book_orders(self) -> None:
        """Test case for order_book_orders

        orderBookOrders
        """
        pass

    def test_order_books(self) -> None:
        """Test case for order_books

        orderBooks
        """
        pass

    def test_recent_trades(self) -> None:
        """Test case for recent_trades

        recentTrades
        """
        pass

    def test_trades(self) -> None:
        """Test case for trades

        trades
        """
        pass


if __name__ == '__main__':
    unittest.main()
