# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.api.block_api import BlockApi


class TestBlockApi(unittest.TestCase):
    """BlockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlockApi()

    def tearDown(self) -> None:
        pass

    def test_block(self) -> None:
        """Test case for block

        block
        """
        pass

    def test_blocks(self) -> None:
        """Test case for blocks

        blocks
        """
        pass

    def test_current_height(self) -> None:
        """Test case for current_height

        currentHeight
        """
        pass


if __name__ == '__main__':
    unittest.main()
