# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.detailed_candlestick import DetailedCandlestick

class TestDetailedCandlestick(unittest.TestCase):
    """DetailedCandlestick unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DetailedCandlestick:
        """Test DetailedCandlestick
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DetailedCandlestick`
        """
        model = DetailedCandlestick()
        if include_optional:
            return DetailedCandlestick(
                timestamp = 1640995200,
                open = 3024.66,
                high = 3034.66,
                low = 3014.66,
                close = 3024.66,
                volume0 = 235.25,
                volume1 = 93566.25,
                last_trade_id = 1,
                trade_count = 1503241
            )
        else:
            return DetailedCandlestick(
                timestamp = 1640995200,
                open = 3024.66,
                high = 3034.66,
                low = 3014.66,
                close = 3024.66,
                volume0 = 235.25,
                volume1 = 93566.25,
                last_trade_id = 1,
                trade_count = 1503241,
        )
        """

    def testDetailedCandlestick(self):
        """Test DetailedCandlestick"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
