# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.ticker import Ticker

class TestTicker(unittest.TestCase):
    """Ticker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ticker:
        """Test Ticker
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ticker`
        """
        model = Ticker()
        if include_optional:
            return Ticker(
                s = 'ETH',
                a = lighter.models.price_level.PriceLevel(
                    price = '3024.66', 
                    size = '0.1', ),
                b = lighter.models.price_level.PriceLevel(
                    price = '3024.66', 
                    size = '0.1', )
            )
        else:
            return Ticker(
                s = 'ETH',
                a = lighter.models.price_level.PriceLevel(
                    price = '3024.66', 
                    size = '0.1', ),
                b = lighter.models.price_level.PriceLevel(
                    price = '3024.66', 
                    size = '0.1', ),
        )
        """

    def testTicker(self):
        """Test Ticker"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
