# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.order_book_depth import OrderBookDepth

class TestOrderBookDepth(unittest.TestCase):
    """OrderBookDepth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderBookDepth:
        """Test OrderBookDepth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderBookDepth`
        """
        model = OrderBookDepth()
        if include_optional:
            return OrderBookDepth(
                code = 200,
                message = '',
                asks = [
                    lighter.models.price_level.PriceLevel(
                        price = '3024.66', 
                        size = '0.1', )
                    ],
                bids = [
                    lighter.models.price_level.PriceLevel(
                        price = '3024.66', 
                        size = '0.1', )
                    ],
                offset = 0
            )
        else:
            return OrderBookDepth(
                code = 200,
                asks = [
                    lighter.models.price_level.PriceLevel(
                        price = '3024.66', 
                        size = '0.1', )
                    ],
                bids = [
                    lighter.models.price_level.PriceLevel(
                        price = '3024.66', 
                        size = '0.1', )
                    ],
                offset = 0,
        )
        """

    def testOrderBookDepth(self):
        """Test OrderBookDepth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
