# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.market_info import MarketInfo

class TestMarketInfo(unittest.TestCase):
    """MarketInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketInfo:
        """Test MarketInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketInfo`
        """
        model = MarketInfo()
        if include_optional:
            return MarketInfo(
                market_id = 1,
                index_price = '3024.66',
                mark_price = '3024.66',
                open_interest = '235.25',
                last_trade_price = '3024.66',
                current_funding_rate = '0.0001',
                funding_rate = '0.0001',
                funding_timestamp = 1640995200,
                daily_base_token_volume = 235.25,
                daily_quote_token_volume = 93566.25,
                daily_price_low = 3014.66,
                daily_price_high = 3024.66,
                daily_price_change = 3.66
            )
        else:
            return MarketInfo(
                market_id = 1,
                index_price = '3024.66',
                mark_price = '3024.66',
                open_interest = '235.25',
                last_trade_price = '3024.66',
                current_funding_rate = '0.0001',
                funding_rate = '0.0001',
                funding_timestamp = 1640995200,
                daily_base_token_volume = 235.25,
                daily_quote_token_volume = 93566.25,
                daily_price_low = 3014.66,
                daily_price_high = 3024.66,
                daily_price_change = 3.66,
        )
        """

    def testMarketInfo(self):
        """Test MarketInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
