# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.order_book import OrderBook

class TestOrderBook(unittest.TestCase):
    """OrderBook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderBook:
        """Test OrderBook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderBook`
        """
        model = OrderBook()
        if include_optional:
            return OrderBook(
                symbol = 'ETH',
                market_id = 1,
                status = 'active',
                taker_fee = '0.0001',
                maker_fee = '0.0000',
                liquidation_fee = '0.01',
                min_base_amount = '0.01',
                min_quote_amount = '0.1',
                supported_size_decimals = 4,
                supported_price_decimals = 4,
                supported_quote_decimals = 4
            )
        else:
            return OrderBook(
                symbol = 'ETH',
                market_id = 1,
                status = 'active',
                taker_fee = '0.0001',
                maker_fee = '0.0000',
                liquidation_fee = '0.01',
                min_base_amount = '0.01',
                min_quote_amount = '0.1',
                supported_size_decimals = 4,
                supported_price_decimals = 4,
                supported_quote_decimals = 4,
        )
        """

    def testOrderBook(self):
        """Test OrderBook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
