# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_tx import ReqGetTx

class TestReqGetTx(unittest.TestCase):
    """ReqGetTx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetTx:
        """Test ReqGetTx
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetTx`
        """
        model = ReqGetTx()
        if include_optional:
            return ReqGetTx(
                by = 'hash',
                value = ''
            )
        else:
            return ReqGetTx(
                by = 'hash',
                value = '',
        )
        """

    def testReqGetTx(self):
        """Test ReqGetTx"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
