# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.req_get_candlesticks import ReqGetCandlesticks

class TestReqGetCandlesticks(unittest.TestCase):
    """ReqGetCandlesticks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReqGetCandlesticks:
        """Test ReqGetCandlesticks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReqGetCandlesticks`
        """
        model = ReqGetCandlesticks()
        if include_optional:
            return ReqGetCandlesticks(
                market_id = 56,
                resolution = '1m',
                start_timestamp = 56,
                end_timestamp = 56,
                count_back = 56,
                set_timestamp_to_end = True
            )
        else:
            return ReqGetCandlesticks(
                market_id = 56,
                resolution = '1m',
                start_timestamp = 56,
                end_timestamp = 56,
                count_back = 56,
        )
        """

    def testReqGetCandlesticks(self):
        """Test ReqGetCandlesticks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
