# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lighter.models.accounts import Accounts

class TestAccounts(unittest.TestCase):
    """Accounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Accounts:
        """Test Accounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Accounts`
        """
        model = Accounts()
        if include_optional:
            return Accounts(
                code = 200,
                message = '',
                total = 1,
                accounts = [
                    lighter.models.account.Account(
                        code = 200, 
                        message = '', 
                        account_type = 1, 
                        index = 1, 
                        l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                        cancel_all_time = 1640995200, 
                        total_order_count = 100, 
                        pending_order_count = 100, 
                        status = 1, 
                        collateral = '46342', )
                    ]
            )
        else:
            return Accounts(
                code = 200,
                total = 1,
                accounts = [
                    lighter.models.account.Account(
                        code = 200, 
                        message = '', 
                        account_type = 1, 
                        index = 1, 
                        l1_address = '0x70997970C51812dc3A010C7d01b50e0d17dc79C8', 
                        cancel_all_time = 1640995200, 
                        total_order_count = 100, 
                        pending_order_count = 100, 
                        status = 1, 
                        collateral = '46342', )
                    ],
        )
        """

    def testAccounts(self):
        """Test Accounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
