# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AccountPosition(BaseModel):
    """
    AccountPosition
    """ # noqa: E501
    market_id: StrictInt
    symbol: StrictStr
    initial_margin_fraction: StrictStr
    open_order_count: StrictInt
    pending_order_count: StrictInt
    position_tied_order_count: StrictInt
    sign: StrictInt
    position: StrictStr
    avg_entry_price: StrictStr
    position_value: StrictStr
    unrealized_pnl: StrictStr
    realized_pnl: StrictStr
    total_funding_paid_out: Optional[StrictStr] = None
    margin_mode: StrictInt
    allocated_margin: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["market_id", "symbol", "initial_margin_fraction", "open_order_count", "pending_order_count", "position_tied_order_count", "sign", "position", "avg_entry_price", "position_value", "unrealized_pnl", "realized_pnl", "total_funding_paid_out", "margin_mode", "allocated_margin"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "market_id": obj.get("market_id"),
            "symbol": obj.get("symbol"),
            "initial_margin_fraction": obj.get("initial_margin_fraction"),
            "open_order_count": obj.get("open_order_count"),
            "pending_order_count": obj.get("pending_order_count"),
            "position_tied_order_count": obj.get("position_tied_order_count"),
            "sign": obj.get("sign"),
            "position": obj.get("position"),
            "avg_entry_price": obj.get("avg_entry_price"),
            "position_value": obj.get("position_value"),
            "unrealized_pnl": obj.get("unrealized_pnl"),
            "realized_pnl": obj.get("realized_pnl"),
            "total_funding_paid_out": obj.get("total_funding_paid_out"),
            "margin_mode": obj.get("margin_mode"),
            "allocated_margin": obj.get("allocated_margin")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


