# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class AccountMarketStats(BaseModel):
    """
    AccountMarketStats
    """ # noqa: E501
    market_id: StrictInt
    daily_trades_count: StrictInt
    daily_base_token_volume: Union[StrictFloat, StrictInt]
    daily_quote_token_volume: Union[StrictFloat, StrictInt]
    weekly_trades_count: StrictInt
    weekly_base_token_volume: Union[StrictFloat, StrictInt]
    weekly_quote_token_volume: Union[StrictFloat, StrictInt]
    monthly_trades_count: StrictInt
    monthly_base_token_volume: Union[StrictFloat, StrictInt]
    monthly_quote_token_volume: Union[StrictFloat, StrictInt]
    total_trades_count: StrictInt
    total_base_token_volume: Union[StrictFloat, StrictInt]
    total_quote_token_volume: Union[StrictFloat, StrictInt]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["market_id", "daily_trades_count", "daily_base_token_volume", "daily_quote_token_volume", "weekly_trades_count", "weekly_base_token_volume", "weekly_quote_token_volume", "monthly_trades_count", "monthly_base_token_volume", "monthly_quote_token_volume", "total_trades_count", "total_base_token_volume", "total_quote_token_volume"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountMarketStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountMarketStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "market_id": obj.get("market_id"),
            "daily_trades_count": obj.get("daily_trades_count"),
            "daily_base_token_volume": obj.get("daily_base_token_volume"),
            "daily_quote_token_volume": obj.get("daily_quote_token_volume"),
            "weekly_trades_count": obj.get("weekly_trades_count"),
            "weekly_base_token_volume": obj.get("weekly_base_token_volume"),
            "weekly_quote_token_volume": obj.get("weekly_quote_token_volume"),
            "monthly_trades_count": obj.get("monthly_trades_count"),
            "monthly_base_token_volume": obj.get("monthly_base_token_volume"),
            "monthly_quote_token_volume": obj.get("monthly_quote_token_volume"),
            "total_trades_count": obj.get("total_trades_count"),
            "total_base_token_volume": obj.get("total_base_token_volume"),
            "total_quote_token_volume": obj.get("total_quote_token_volume")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


