# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from lighter.models.daily_return import DailyReturn
from typing import Optional, Set
from typing_extensions import Self

class PublicPoolInfo(BaseModel):
    """
    PublicPoolInfo
    """ # noqa: E501
    status: StrictInt
    operator_fee: StrictStr
    min_operator_share_rate: StrictStr
    total_shares: StrictInt
    operator_shares: StrictInt
    share_price_1d: Union[StrictFloat, StrictInt]
    share_price_7d: Union[StrictFloat, StrictInt]
    share_price_30d: Union[StrictFloat, StrictInt]
    annual_percentage_yield: Union[StrictFloat, StrictInt]
    daily_returns: List[DailyReturn]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["status", "operator_fee", "min_operator_share_rate", "total_shares", "operator_shares", "share_price_1d", "share_price_7d", "share_price_30d", "annual_percentage_yield", "daily_returns"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicPoolInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in daily_returns (list)
        _items = []
        if self.daily_returns:
            for _item in self.daily_returns:
                if _item:
                    _items.append(_item.to_dict())
            _dict['daily_returns'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicPoolInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "operator_fee": obj.get("operator_fee"),
            "min_operator_share_rate": obj.get("min_operator_share_rate"),
            "total_shares": obj.get("total_shares"),
            "operator_shares": obj.get("operator_shares"),
            "share_price_1d": obj.get("share_price_1d"),
            "share_price_7d": obj.get("share_price_7d"),
            "share_price_30d": obj.get("share_price_30d"),
            "annual_percentage_yield": obj.get("annual_percentage_yield"),
            "daily_returns": [DailyReturn.from_dict(_item) for _item in obj["daily_returns"]] if obj.get("daily_returns") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


